# Generated by Django 5.2 on 2025-04-22 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('category_id', models.IntegerField(choices=[(1, 'environmental & sanitation issues'), (2, 'infrastructure issues'), (3, 'public safety issue'), (4, 'utilities & public service'), (5, 'community and public service maintenance'), (6, 'Health and emergency concern')], default=1)),
                ('description', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'mild'), (2, 'moderate'), (3, 'severe')], default=1)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image_url', models.ImageField(blank=True, default='pending', null=True, upload_to='report')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
