# Generated by Django 5.2 on 2025-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
    ]
